apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.github: ""
spec:
  project: prod
  source:
    repoURL: https://github.com/mahdibouaziz/argo-lab
    targetRevision: main
    path: apps/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
