---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: https://238b32414a02.ngrok-free.app

  service.github: |
    appID: 1555506
    installationID: 74982098
    privateKey: $github-privateKey

  trigger.on-sync-succeeded: |
    - when: app.status.sync.status == 'Synced' and app.status.health.status == 'Healthy'
      send:
        - github-app-deploy-notification

  # Working Perfectly and tested
  template.github-app-deploy-notification: |
    message: |
      App {{.app.metadata.name}} deployed successfully.
    github:
      pullRequestComment:
        content: |
          ✅ **{{.app.metadata.name}}** has been deployed successfully!
